[package]
name = "nba-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
maplit = "1.0.2"
paste = "1.0.7"
rand = "0.8.5"
reqwest = { version = "0.11.11", features = ["json", "gzip"] }
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"
tokio = { version = "1.20.0", features = ["full"] }

[build-dependencies]
anyhow = "1.0.58"
heck = "0.4.0"
quote = "1.0.20"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
