[package]
name = "nba"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.58"
heck = "0.4.0"
once_cell = "1.16.0"
reqwest = { version = "0.11.11", features = ["json", "gzip"] }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"

[dev-dependencies]
color-eyre = "0.6.2"
tokio = { version = "1.21.2", features = ["full"] }
