use super::PlayersGeneralParameters;
use crate::fields::MeasureType;

crate::endpoint! {
    PlayersScoring(PlayersGeneralParameters): "leaguedashplayerstats" => {
        measure_type: MeasureType::Scoring,
    } => {
        league_dash_player_stats: LeagueDashPlayerStatsRow("LeagueDashPlayerStats") {
            player_id: u32,
            player_name: String,
            nickname: String,
            team_id: u32,
            team_abbreviation: String,
            age: f64,
            gp: u32,
            w: u32,
            l: u32,
            w_pct: f64,
            min: f64,
            pct_fga_2pt: f64,
            pct_fga_3pt: f64,
            pct_pts_2pt: f64,
            pct_pts_2pt_mr: f64,
            pct_pts_3pt: f64,
            pct_pts_fb: f64,
            pct_pts_ft: f64,
            pct_pts_off_tov: f64,
            pct_pts_paint: f64,
            pct_ast_2pm: f64,
            pct_uast_2pm: f64,
            pct_ast_3pm: f64,
            pct_uast_3pm: f64,
            pct_ast_fgm: f64,
            pct_uast_fgm: f64,
            fgm: u32,
            fga: u32,
            fg_pct: f64,
            gp_rank: u32,
            w_rank: u32,
            l_rank: u32,
            w_pct_rank: u32,
            min_rank: u32,
            pct_fga_2pt_rank: u32,
            pct_fga_3pt_rank: u32,
            pct_pts_2pt_rank: u32,
            pct_pts_2pt_mr_rank: u32,
            pct_pts_3pt_rank: u32,
            pct_pts_fb_rank: u32,
            pct_pts_ft_rank: u32,
            pct_pts_off_tov_rank: u32,
            pct_pts_paint_rank: u32,
            pct_ast_2pm_rank: u32,
            pct_uast_2pm_rank: u32,
            pct_ast_3pm_rank: u32,
            pct_uast_3pm_rank: u32,
            pct_ast_fgm_rank: u32,
            pct_uast_fgm_rank: u32,
            fgm_rank: u32,
            fga_rank: u32,
            fg_pct_rank: u32,
            cfid: u32,
            cfparams: String,
        },
    }
}
